Tools/YamlCreate.ps1

GitHub desktop didn't let me open a PR but GitHub web did >_>

Git error handling

---

Tools/YamlCreate.ps1

-----
Updated method of getting Product Code from the installer which works on PS5 and PS5+.

Update method of getting Product Code from installer

---

Tools/YamlCreate.ps1

Resolves https://github.com/microsoft/winget-pkgs/issues/24066

SignatureSha256 and PackageFamilyName

---

Tools/YamlCreate.ps1

Hmm, not sure if it should be `Add Version` or `New Version`, i kinda like `New Version` tbh

Differentiate between Upgrade and New Version

---

Tools/YamlCreate.ps1

Exclude .validation

---

Tools/YamlCreate.ps1

Fix for https://github.com/Trenly/winget-pkgs/pull/8#issuecomment-895113872

Add new line for PackageFamilyName

---

Tools/YamlCreate.ps1

@OfficialEsco @vedantmgoyal2009
I noticed most of the menus were similar, so I made a function to help reduce duplicated code. Please review

Standardize Keypress Menus

---

Tools/YamlCreate.ps1

@OfficialEsco This should resolve these three comments I made in #12 
- Handles issues which contain a `#` in them or which are from other repositories (e.g `trenly/winget-pkgs#12`)
- Checks issue validity by seeing if the URL returns a valid response code
- Reduces duplicate code by moving the showing of the menu outside of the switch for the PrBodyContentReply
I've done some light testing, see microsoft/winget-pkgs#24579
(I'll look into the parameters issue you mentioned separately)

Menu reduction

---

Tools/YamlCreate.ps1

@OfficialEsco I haven't gotten it finished yet, but since I was looking at validating the Installer URL from your [Comment](https://github.com/microsoft/winget-pkgs/pull/21204#discussion_r690505374) I decided to add in a custom class for us to do the error checking and feedback to users. 
Let me know what you think. If you like it, we can use this for error checking all the other fields.

Add Custom Error Class

---

Tools/YamlCreate.ps1

@OfficialEsco - Could I trouble you for a review?
As a side note, I decided to not have it enumerate every single one of the fields available under `Installers:`  just because it got to be a lot (especially with more than one installer). Everything else should work though

Write Unused Keys as Comments

---

Tools/YamlCreate.ps1

Fix InstallModes

---

Tools/YamlCreate.ps1

Resolves #30 
------
@OfficialEsco I've begun handling and condensing parameters to and from the manifest level. I haven't tested this at all yet, but I'm 80% confident the main functionality is there if you'd like to help me find the bugs.
I still want to complete the rework to update the manifests in-place as part of this too, but I don't think that needs to be complete to test.

Begin Handling Manifest Level Parameters

---

Tools/YamlCreate.ps1

Fix: Update SignatureSha256 in quick update mode

---

Tools/YamlCreate.ps1
doc/tools/YamlCreate.md

Change Settings to allow for negative suppression

---

Tools/YamlCreate.ps1

full title instead of just the PR Number when adding Resolves in the PR

---

Tools/YamlCreate.ps1

- #49
This fixes the spacing issue in the PR body.
@OfficialEsco

Fix spacing issue [#49]

---

Tools/YamlCreate.ps1

@vedantmgoyal2009
* Resolves #45

Fix: Prompt for PFN if file does not exist

---

Tools/YamlCreate.ps1
doc/tools/YamlCreate.md

@OfficialEsco  Is this what you were thinking in https://github.com/Trenly/winget-pkgs/pull/58#issuecomment-927187442 ?

Make Simple Update automatically detect Sha256, SignatureSha256, and ProductCode without prompts

---

Tools/YamlCreate.ps1

Fix for https://github.com/vedantmgoyal2009/winget-pkgs-automation/runs/3862393143?check_suite_focus=true#step:3:952

Add is:pr to exclude issues from results

---

README.md

fix very minor error

---

manifests/l/Lexikos/AutoHotkey/1.1.33.10/Lexikos.AutoHotkey.installer.yaml

Use Vanity URL

---

Tools/YamlCreate.ps1

Decided to go through and update a few more function names

More function name updates

---

Tools/YamlCreate.ps1

https://github.com/Trenly/winget-pkgs/pull/107#issuecomment-953985103

Check for version when setting proxy

---

Tools/YamlCreate.ps1

* Resolves https://github.com/Trenly/winget-pkgs/issues/121

Fix yaml-language-server comment

---

Tools/YamlCreate.ps1

@OfficialEsco 
- Resolves #128

Fix Architecture Overwriting

---

Tools/YamlCreate.ps1

- Resolves #123 
@OfficialEsco

Preserve Product Codes on exe files

---

Tools/YamlCreate.ps1

@OfficialEsco 
- Resolves #119 
- Resolves #118

Make items lowercase and remove whitespaces

---

Tools/YamlCreate.ps1

@OfficialEsco 
- Resolves #131

Fix Trenly/winget-pkgs#131

---

Tools/YamlCreate.ps1

* Resolve powershell-yaml before checking settings to prevent this error:
-----
* Do not execute `Get-AppLockerFileInformation` since it is only available on Windows and not Linux/macOS.

Minor bug fixes and enhancements

---

Tools/YamlCreate.ps1

Fix: Use combined hashes

---

Tools/YamlCreate.ps1

* Resolves Trenly/winget-pkgs#142
-----

Fix: Add UserAgent

---

Tools/YamlCreate.ps1

Use less intensive matching

---

Tools/YamlCreate.ps1

@OfficialEsco 
* Resolves #154

SignatureSha256 fix

---

Tools/YamlCreate.ps1

@Trenly @OfficialEsco @jedieaston

Use Invoke-RestMethod instead of Invoke-WebRequest

---

Tools/YamlCreate.ps1

Fix: Don't commit files outside of ./manifests/*

---

Tools/YamlCreate.ps1

@jedieaston
@OfficialEsco 
@spectershell
This should resolve #159

Fix: Test filename for validity before downloading

---

Tools/YamlCreate.ps1

fix: git add command

---

Tools/YamlCreate.ps1

Even if there is a `throw` in `catch` scriptblock, PowerShell still invokes `finally` scriptblock after that.

No finally scriptblock after downloading error (Trenly/winget-pkgs#176)

---

manifests/m/MongoDB/Server/6.0.6/MongoDB.Server.locale.en-US.yaml

- Merges into https://github.com/microsoft/winget-pkgs/pull/131316
---

Fix LicenseUrl to unblock PR

---

Tools/SandboxTest.ps1

- Remove `-preview` from preview release tags for comparison as `[System.Version]` cast fails otherwise
- `1.7.10514-preview` appears to be the minimum version that requires Xaml 2.8.6
- Fix condition for checking hash
- Properly quote `'$($dependencySource)'` which was previously being interpreted as a command causing the script to always go the `catch` case
---

Sandbox fixes

---

Tools/SandboxTest.ps1

- `$rateLimit[0]` needs to be explicitly cast to `int` as the array I get is of type `string`
- `ToString()` omits year from the date for me which results it being not parsed correctly at `[System.DateTime]::TryParse($cachedExpirationForParsing, [ref]$cachedExpirationDate)` & going to the error `'The cached token contained content, but it could not be parsed as a date. It will be re-validated'`. Using `ToLongDateString()` retains the year and would get parsed correctly.
- Added a case for never expire instead of showing that it would expire in some 2 hundred thousand days later
- Some typo fixes and output suppression
---

Some improvements

---

Tools/YamlCreate_Proper.ps1

- AppxBlockMap.xml for MSIX heuristic search
- Fix condition for inno where it was incorrectly looking in the wrong field for equality
- ResourceType doesn't appear to be a valid parameter
---

Some updates
